CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2 `pkg-config --cflags gtkmm-3.0`
LDFLAGS = `pkg-config --libs gtkmm-3.0`

OBJS = domino.o
TARGETS = demo1 demo2

all: $(TARGETS)

demo1: demo1.cpp
	$(CXX) $(CXXFLAGS) demo1.cpp -o demo1 $(LDFLAGS)

demo2: demo2.cpp $(OBJS)
	$(CXX) $(CXXFLAGS) demo2.cpp domino.o -o demo2 $(LDFLAGS)

domino.o: domino.cpp domino.h
	$(CXX) $(CXXFLAGS) -c domino.cpp

clean:
	rm -f $(TARGETS) *.o

.PHONY: all clean
